#!/bin/bash
update-alternatives --install /usr/bin/pbskids-dl pbskids-dl /usr/lib/pbskids-dl/pbskids-dl.py 100
update-alternatives --install /usr/bin/pbskids-dl_gui pbskids-dl_gui /usr/lib/pbskids-dl/pbskids-dl_gui.py 100
